apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: bluecompute
    micro: web-bff
    tier: frontend
    implementation: microprofile
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  checks: "# Check the main website, including text content\r\n/\tIBM Cloud Architecture\r\n\r\n#Check
    the Inventory page\r\n/catalog/ Dayton Meat Chopper\r\n\r\n# Check for stylesheets
    and for text content in stylesheets\r\n/stylesheets/font-awesome/font-awesome.css
    \   @font-face\r\n\r\n\r\n# Check a sub-domain\r\n#//some-subdomain.some-site.com/reviews
    Review Data\r\n\r\n# Check HTTP access, and for text content\r\n# http://localhost:8000\tBlueCompute
    Store!\r\n# http://localhost:8000/inventory/\tDayton Meat Chopper\r\n"
  default.json: |
    {
      "Application": {
        "cluster_name": "",
        "region": ""
      },
      "Auth-Server": {
        "client_id":"bluecomputeweb",
        "client_secret":"bluecomputewebs3cret"
      },
      "APIs": {
        "protocol": "http",
        "protocols": "https",
        "catalog": {
          "service_name": "{{ .Release.Name }}-catalog:9080/catalog",
          "base_path": "/rest",
          "require": [
          ]
        },
        "order": {
          "service_name": "{{ .Release.Name }}-orders:9443/orders",
          "base_path": "/rest",
          "require": [
            "oauth"
          ]
        },
        "review": {
          "base_path": "/api",
          "require": [
            "oauth"
          ]
        },
        "customerService": {
          "service_name": "{{ .Release.Name }}-customer:9443/customer",
          "base_path": "/rest",
          "paths": {
            "customer": "/customer"
          },
          "require": [
              "oauth"
          ],
          "redirect_url": "http://localhost"
        },
        "customer": {
            "service_name": "{{ .Release.Name }}-auth:9443/oidc/endpoint",
            "base_path": "/OP",
            "paths": {
              "userinfo": "/userinfo"
            },
            "require": [
              "oauth"
            ],
            "redirect_url": "http://localhost"
        },
        "oauth20": {
          "protocol": "https",
          "service_name": "{{ .Release.Name }}-auth:9443/oidc/endpoint",
          "base_path": "/OP",
          "paths": {
            "authz": "/authorize",
            "token": "/token"
          },
          "grant_types": [
            "password"
          ],
          "scopes": [
            "bluecompute"
          ],
          "redirect_url": "http://localhost"
        }
      }
    }
