apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: bluecompute
    micro: web-bff
    tier: frontend
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        micro: web-bff
        tier: frontend
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ template "dockerImage" . }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /StoreWebApp/config
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-config
          items:
          - key: checks
            path: checks
          - key: default.json
            path: default.json
