{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "web.fullname" . }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "web.labels" . | indent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "web.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
  {{- if .Values.ingress.hostname }}
    host: .Values.ingress.hostname | quote }}
  {{- end }}
{{- if .Values.ingress.enableTLS }}
  tls:
{{ toYaml .Values.ingress.TLS | indent 2 }}
{{- end }}
{{- end }}
