{{ if or .Values.global.istio.enabled .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "web.fullname" . }}
spec:
  hosts:
  {{- if and .Values.istio.enableGateway .Values.istio.hosts }}
{{ toYaml .Values.istio.hosts | indent 2 }}
  {{- else if .Values.istio.enableGateway }}
  - "*"
  {{- else }}
  - {{ template "web.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- end }}
  {{- if .Values.istio.enableGateway }}
  gateways:
  - {{ template "web.fullname" . }}-gateway
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ template "web.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.externalPort }}
        subset: v1
{{ end }}