apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bluecompute
    micro: web-bff
    tier: frontend
    implementation: microprofile
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
{{ if eq .Values.service.type "NodePort" }}
{{ if .Values.service.nodeport.port }}
    nodePort: {{ .Values.service.nodeport.port }}
{{ end }}
{{ end }}
  selector:
    app: bluecompute
    micro: web-bff
    tier: frontend
    implementation: microprofile
