---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bluecompute-web-depoyment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bluecompute
        tier: frontend
        micro: web-bff
    spec:
      containers:
      - name: bluecompute-web
        image: registry.ng.bluemix.net/chrisking/bluecompute-web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bluecompute-web
  labels:
    app: bluecompute
    tier: frontend
    micro: web-bff
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: bluecompute
    tier: frontend
    micro: web-bff
  type: LoadBalancer
...
