apiVersion: v1
description: BlueCompute Web BFF app
name: web
version: 0.0.1
home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
sources:
  - https://github.com/ibm-cloud-architecture/refarch-cloudnative-bluecompute-web/tree/microprofile
