# Default values for bluecompute-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  #repository: registry.csplab.cloudns.cx/microprofile/bc-web-mp
  #repository: bc-web-mp
  repository: web
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: bluecompute-web
  type: NodePort
  externalPort: 80
  internalPort: 8000
  nodeport:
    port:
ingress:
  hostname:
  path: /bluecompute-mp
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
region:
clusterName:
services:
  auth:
    host:
    port:
  catalog:
    host:
    port:
  customer:
    host:
    port:
  orders:
    host:
    port:
  reviews:
    host:
    port:

global:
  bluemix:
    apiKey:

    target:
      endpoint:
      org:
      space:

    clusterName:
