replicaCount: 1

image:
  repository: ibmcase/bluecompute-web
  tag: 0.5.0
  pullPolicy: Always

service:
  type: NodePort
  externalPort: 80
  internalPort: 8000
  nodePort: 31337

ingress:
  enabled: false
  hostname:
  path: /

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY
  ibmCloud:
    redirectToHTTPS: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

cluster:
  name:
  region:

services:
  auth:
    protocol: http
    host:
    port:
  catalog:
    protocol: http
    host:
    port:
  customer:
    protocol: http
    host:
    port:
  orders:
    protocol: http
    host:
    port:
  reviews:
    protocol: http
    host:
    port:

global:
  cluster:
    name:
    region: